version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
    expose:
      - ${POSTGRES_PORT}
    networks:
      - chatbot-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  chatbot-network:
    driver: bridge
